import AppKit

struct ClipItem: Identifiable, Equatable, Codable {
    enum Payload: Equatable {
        case text(String)
        case file(URL)
    }

    var id = UUID()
    let payload: Payload
    let date: Date
    /// Pinned entries sit above the rest, are never pushed out, and survive
    /// "Clear". Only an explicit unpin makes them ordinary again.
    var isPinned = false

    init(payload: Payload, date: Date, isPinned: Bool = false) {
        self.payload = payload
        self.date = date
        self.isPinned = isPinned
    }

    var preview: String {
        switch payload {
        case .text(let string):
            return string.trimmingCharacters(in: .whitespacesAndNewlines)
        case .file(let url):
            return url.lastPathComponent
        }
    }

    var symbol: String {
        switch payload {
        case .text(let string):
            if string.hasPrefix("http://") || string.hasPrefix("https://") { return "link" }
            return "text.alignleft"
        case .file:
            return "doc"
        }
    }

    static func == (lhs: ClipItem, rhs: ClipItem) -> Bool { lhs.payload == rhs.payload }

    // MARK: - File format

    /// `{"text": "…"}` or `{"file": "/path"}`, plus `date` and `pinned`. The id
    /// is not stored: it only has to be stable within one launch.
    private enum CodingKeys: String, CodingKey { case text, file, date, pinned }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        if let text = try c.decodeIfPresent(String.self, forKey: .text) {
            payload = .text(text)
        } else {
            payload = .file(URL(fileURLWithPath: try c.decode(String.self, forKey: .file)))
        }
        date = try c.decodeIfPresent(Date.self, forKey: .date) ?? Date()
        isPinned = try c.decodeIfPresent(Bool.self, forKey: .pinned) ?? false
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        switch payload {
        case .text(let string): try c.encode(string, forKey: .text)
        case .file(let url): try c.encode(url.path, forKey: .file)
        }
        try c.encode(date, forKey: .date)
        if isPinned { try c.encode(true, forKey: .pinned) }
    }
}

/// Polls the general pasteboard's change counter. Cheap: one integer read
/// twice a second, and nothing at all is read until the counter moves.
///
/// No limit on the history, and it outlives relaunches: text and file
/// references go to `clipboard.json`, a moment after the last change, through
/// `DebouncedWrite`. Pictures never do — they are saved as files and go to the
/// shelf instead.
@MainActor
final class ClipboardStore: ObservableObject {
    /// Pinned first, newest first within each group.
    @Published private(set) var items: [ClipItem] = []

    /// Raised for image data on the pasteboard — a screenshot taken straight to
    /// the clipboard, which would otherwise vanish after one paste.
    var onImage: ((Data) -> Void)?

    /// Whether images are worth reading at all. Asked before the TIFF → PNG
    /// encode, not after: with screenshot saving switched off, a copied picture
    /// would otherwise be encoded in full and then thrown away.
    var wantsImages: () -> Bool = { true }

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let saves = DebouncedWrite(after: 1.0)

    /// `~/Library/Application Support/OdinsEye/clipboard.json`. Given rather
    /// than looked up so a test never touches the real history.
    let file: URL

    init(file: URL = Support.file("clipboard.json")) {
        self.file = file
        load()
    }

    /// Types an app sets to keep a copy out of history tools. Presence is what
    /// counts, not content: a type can be declared with data that is still on
    /// its way, and asking for the bytes would then answer nil for a password
    /// that is about to arrive. `ConcealedType` is what password managers set;
    /// the other two mark copies made by a machine rather than by a hand.
    private let optOut: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    func start() {
        stop()
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // The half-second is a ceiling, not a beat: nobody notices a copy
        // landing in history a fifth of a second late, and the slack lets the
        // system fold this wake-up into others.
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Everything except the pinned entries.
    func clear() {
        items.removeAll { !$0.isPinned }
        scheduleSave()
    }

    var hasUnpinned: Bool { items.contains { !$0.isPinned } }

    func remove(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
        scheduleSave()
    }

    /// Pinning moves the entry to the top of the pinned group; unpinning, to
    /// the top of the rest.
    func togglePin(_ item: ClipItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        var entry = items.remove(at: index)
        entry.isPinned.toggle()
        insert(entry)
    }

    /// Puts an entry back on the pasteboard without re-recording it.
    func copy(_ item: ClipItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch item.payload {
        case .text(let string):
            pasteboard.setString(string, forType: .string)
        case .file(let url):
            pasteboard.writeObjects([url as NSURL])
        }
        lastChangeCount = pasteboard.changeCount
        // Freshly used entries bubble to the top of their group.
        if let index = items.firstIndex(where: { $0.id == item.id }) {
            insert(items.remove(at: index))
        }
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        guard pasteboard.availableType(from: optOut) == nil else { return }
        // Our own write — copying a screenshot back out of the shelf must not
        // save it to disk all over again.
        guard pasteboard.data(forType: .ownWrite) == nil else { return }

        // A copied file arrives as a URL, not as image data, so URLs win first.
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
           let url = urls.first {
            record(ClipItem(payload: .file(url), date: Date()))
            return
        }

        if wantsImages() {
            if let png = pngFromPasteboard(pasteboard) {
                onImage?(png)
                return
            }

            // A copy made on the phone arrives in two parts: macOS puts the
            // type on the pasteboard the moment the phone announces it, and
            // the picture itself is still coming over the air. So the counter
            // can move while there are no bytes to read yet — and reading once
            // would drop the screenshot for good, because the counter has
            // already been marked as seen. Wait for it instead.
            if pasteboard.availableType(from: [.png, .tiff]) != nil {
                awaitImage(at: pasteboard.changeCount, attempt: 0)
                return
            }
        }

        guard let string = pasteboard.string(forType: .string),
              !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        record(ClipItem(payload: .text(string), date: Date()))
    }

    /// Checks back until the promised picture has actually arrived.
    ///
    /// Gives up after a few seconds, and stops the moment the pasteboard moves
    /// on: a copy made in the meantime is the newer intention, and finishing a
    /// transfer the user has already replaced would put the wrong thing on the
    /// shelf.
    private func awaitImage(at changeCount: Int, attempt: Int) {
        // Out of patience. Something declared a picture and never produced one,
        // so fall back to what else was on the pasteboard — otherwise a copy
        // that merely offered an image alongside its text would go unrecorded.
        guard attempt < 12 else {
            let pasteboard = NSPasteboard.general
            guard pasteboard.changeCount == changeCount,
                  let string = pasteboard.string(forType: .string),
                  !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
            record(ClipItem(payload: .text(string), date: Date()))
            return
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [weak self] in
            MainActor.assumeIsolated {
                guard let self else { return }
                let pasteboard = NSPasteboard.general
                guard pasteboard.changeCount == changeCount else { return }
                if let png = self.pngFromPasteboard(pasteboard) {
                    self.onImage?(png)
                    return
                }
                self.awaitImage(at: changeCount, attempt: attempt + 1)
            }
        }
    }

    /// Screenshots land as PNG; other apps often offer only TIFF.
    private func pngFromPasteboard(_ pasteboard: NSPasteboard) -> Data? {
        if let png = pasteboard.data(forType: .png) { return png }
        guard let tiff = pasteboard.data(forType: .tiff),
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    /// A new copy goes on top of the unpinned entries. Copying something that
    /// is already in the history moves it instead, keeping its pin and its id.
    func record(_ item: ClipItem) {
        var item = item
        if let index = items.firstIndex(of: item) {
            let existing = items.remove(at: index)
            item.id = existing.id
            item.isPinned = existing.isPinned
        }
        insert(item)
    }

    private func insert(_ item: ClipItem) {
        let index = item.isPinned ? 0 : (items.firstIndex { !$0.isPinned } ?? items.count)
        items.insert(item, at: index)
        scheduleSave()
    }

    // MARK: - Persistence

    private func load() {
        guard let data = try? Data(contentsOf: file) else { return }
        do {
            let stored = try JSONDecoder.clipboard.decode([ClipItem].self, from: data)
            // Pinned first whatever order the file had them in.
            items = stored.filter(\.isPinned) + stored.filter { !$0.isPinned }
        } catch {
            NSLog("OdinsEye: clipboard.json is not readable: \(error.localizedDescription)")
        }
    }

    private func scheduleSave() {
        saves.schedule { [weak self] in self?.persist() }
    }

    /// Writes whatever is waiting now — on quit.
    func flush() { saves.flush() }

    /// Readable by the owner only: the history is whatever was copied, and
    /// that is often something private even when no password manager marked it.
    private func persist() {
        do {
            try JSONEncoder.clipboard.encode(items).write(to: file, options: .atomic)
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: file.path)
        } catch {
            NSLog("OdinsEye: cannot write clipboard.json: \(error.localizedDescription)")
        }
    }
}

private extension JSONEncoder {
    static var clipboard: JSONEncoder {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        return encoder
    }
}

private extension JSONDecoder {
    static var clipboard: JSONDecoder {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return decoder
    }
}
